# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/lib" -L"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"F:/Code/C/Breakout/lib" -static-libgcc -g3
INCS     = -I"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/include" -I"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"F:/Code/C/Breakout/include"
CXXINCS  = -I"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/include" -I"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Downloaded Utility Programs/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = brkout.exe
CXXFLAGS = $(CXXINCS) -g3 -g
CFLAGS   = $(INCS) -g3 -g
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
